name: Start kube-burner
description: Starts kube-burner to create load for ACS
inputs:
  kube-burner-config-dir:
    description: Where the config files for kube-burner-are-located
    required: true
    default: ""
  benchmark-operator-dir:
    description: Where the benchmark-operator directory is located
    required: true
    default: ""

runs:
  using: composite
  steps:
    - env:
        KUBE_BURNER_CONFIG_DIR: ${{ inputs.kube-burner-config-dir }}
        BENCHMARK_OPERATOR_DIR: ${{ inputs.benchmark-operator-dir }}
      run: |
        set -uo pipefail
        "${{ github.action_path }}/../../common/common.sh" \
          "${{ github.action_path }}/start-kube-burner.sh"

      shell: bash
