apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-burner
  namespace: kube-burner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-burner
  template:
    metadata:
      labels:
        app: kube-burner
    spec:
      containers:
      - name: kube-burner
        image: quay.io/kube-burner/kube-burner:v1.4.3
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -x
            cd /etc/kube-burner && \
            config=config.yml && \
            metrics_profile=/etc/kube-burner-metrics/metrics.yml && \
            prometheus_url="http://monitoring.stackrox.svc.cluster.local:9090" && \
            (kube-burner init --config="$config" --metrics-profile="$metrics_profile" --prometheus-url="$prometheus_url" || true) & \
            sleep 30m && \
            kube-burner index --config="$config" --metrics-profile="$metrics_profile" --prometheus-url="$prometheus_url" --uuid="$UUID"
        volumeMounts:
        - name: config
          mountPath: "/etc/kube-burner"
          readOnly: true
        - name: metrics
          mountPath: "/etc/kube-burner-metrics"
        env:
        - name: ELASTICSEARCH_URL
          valueFrom:
            secretKeyRef:
              name: kube-burner-secret
              key: ELASTICSEARCH_URL
        - name: UUID
          valueFrom:
            secretKeyRef:
              name: kube-burner-secret
              key: UUID
      volumes:
      - name: config
        configMap:
          name: kube-burner-config
      - name: metrics
        configMap:
          name: kube-burner-metrics-config
          items:
          - key: metrics.yml
            path: metrics.yml
      serviceAccount: kube-burner
      serviceAccountName: kube-burner

