apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-burner
  namespace: kube-burner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-burner
  template:
    metadata:
      labels:
        app: kube-burner
    spec:
      containers:
      - name: kube-burner
        image: quay.io/kube-burner/kube-burner:v2.6.2
        command: ["/bin/sh", "-c"]
        args:
          - |
            get_epoch_time() {
              curl -G --silent http://monitoring.stackrox.svc.cluster.local:9090/api/v1/query --data-urlencode 'query=time()' | sed 's|.*\[||' | sed 's|\..*||'
            }
            cd /etc/kube-burner
            config=berserker-load.yml
            metrics_profile=/etc/kube-burner-metrics/metrics.yml
            prometheus_url="http://monitoring.stackrox.svc.cluster.local:9090"
            (kube-burner init --config="$config" --skip-log-file --timeout=1000h \
              --set GC="$GC" \
              --set GC_METRICS="$GC_METRICS" \
              --set DELETION_STRATEGY="$DELETION_STRATEGY" \
              --set POD_READY_THRESHOLD="$POD_READY_THRESHOLD" \
              --set ES_SERVER="$ES_SERVER" \
              --set ES_INDEX="$ES_INDEX" \
              --set LOCAL_INDEXING="$LOCAL_INDEXING" \
              --set METRICS="$METRICS" \
              --set ALERTS="$ALERTS" \
              --set UUID="$UUID" \
              --set JOB_ITERATIONS="$JOB_ITERATIONS" \
              --set JOB_PAUSE="$JOB_PAUSE" \
              --set QPS="$QPS" \
              --set BURST="$BURST" \
              --set CHURN_CYCLES="$CHURN_CYCLES" \
              --set CHURN_DURATION="$CHURN_DURATION" \
              --set CHURN_DELAY="$CHURN_DELAY" \
              --set CHURN_PERCENT="$CHURN_PERCENT" \
              --set CHURN_MODE="$CHURN_MODE" \
              --set MAX_WAIT_TIMEOUT="$MAX_WAIT_TIMEOUT" \
              --set DAEMONSET_REPLICAS="$DAEMONSET_REPLICAS" \
              --set SERVICE_REPLICAS="$SERVICE_REPLICAS" \
              || true) &
            while true; do
              start="$(get_epoch_time)"
              sleep "$METRICS_COLLECTION_TIME"
              end="$(get_epoch_time)"
              kube-burner index --metrics-profile="$metrics_profile" --prometheus-url="$prometheus_url" --start "$start" --end "$end" --step "$METRICS_TIME_STEP" --uuid="$UUID" --es-server "$ELASTICSEARCH_URL" --es-index kube-burner-long-running-test
            done
        volumeMounts:
        - name: config
          mountPath: "/etc/kube-burner"
          readOnly: true
        - name: metrics
          mountPath: "/etc/kube-burner-metrics"
        env:
        - name: ELASTICSEARCH_URL
          valueFrom:
            secretKeyRef:
              name: kube-burner-secret
              key: ELASTICSEARCH_URL
        - name: UUID
          valueFrom:
            secretKeyRef:
              name: kube-burner-secret
              key: UUID
        - name: METRICS_COLLECTION_TIME
          valueFrom:
            secretKeyRef:
              name: kube-burner-secret
              key: METRICS_COLLECTION_TIME
        - name: METRICS_TIME_STEP
          valueFrom:
            secretKeyRef:
              name: kube-burner-secret
              key: METRICS_TIME_STEP
        - name: GC
          value: "true"
        - name: GC_METRICS
          value: "false"
        - name: DELETION_STRATEGY
          value: "gvr"
        - name: POD_READY_THRESHOLD
          value: "5m0s"
        - name: ES_SERVER
          value: ""
        - name: ES_INDEX
          value: ""
        - name: LOCAL_INDEXING
          value: "false"
        - name: METRICS
          value: "metrics.yml"
        - name: ALERTS
          value: ""
        - name: JOB_ITERATIONS
          value: "5"
        - name: JOB_PAUSE
          value: "0s"
        - name: QPS
          value: "20"
        - name: BURST
          value: "20"
        - name: CHURN_CYCLES
          value: "0"
        - name: CHURN_DURATION
          value: "0s"
        - name: CHURN_DELAY
          value: "10m0s"
        - name: CHURN_PERCENT
          value: "80"
        - name: CHURN_MODE
          value: "objects"
        - name: MAX_WAIT_TIMEOUT
          value: "12m0s"
        - name: DAEMONSET_REPLICAS
          value: "6"
        - name: SERVICE_REPLICAS
          value: "6"
        - name: BERSERKER_CONFIGMAP_TEMPLATE
          valueFrom:
            secretKeyRef:
              name: kube-burner-secret
              key: BERSERKER_CONFIGMAP_TEMPLATE
        - name: BERSERKER_SERVICE_TEMPLATE
          valueFrom:
            secretKeyRef:
              name: kube-burner-secret
              key: BERSERKER_SERVICE_TEMPLATE
        - name: BERSERKER_CONTAINERS_FILE
          valueFrom:
            secretKeyRef:
              name: kube-burner-secret
              key: BERSERKER_CONTAINERS_FILE
      volumes:
      - name: config
        configMap:
          name: kube-burner-config
      - name: metrics
        configMap:
          name: kube-burner-metrics-config
          items:
          - key: metrics.yml
            path: metrics.yml
      serviceAccount: kube-burner
      serviceAccountName: kube-burner

