name: Start the secured cluster
description: Starts the secured cluster for the long running cluster
inputs:
  main-image-tag:
    description: The image tag used for the main image and other images
    required: true
    default: ""
  kubeconfig:
    description: The kubeconfig file used to connect to kubernetes
    required: true
    default: ""
  pagerduty-integration-key:
    description: The key that will be used to send pager duty alerts
    required: false
    default: ""
  registry-username:
    description: The username used for the docker registry
    required: true
    default: ""
  registry-password:
    description: The password used for the docker registry
    required: true
    default: ""
  rox-admin-password:
    description: The password for central
    required: true
    default: ""
  central-ip:
    description: The IP address for central
    required: true
    default: ""

runs:
  using: composite
  steps:
    - name: Docker login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - id: launch-secured-cluster
      env:
        MAIN_IMAGE_TAG: ${{ inputs.main-image-tag }}
        REGISTRY_USERNAME: ${{ inputs.registry-username }}
        REGISTRY_PASSWORD: ${{ inputs.registry-password }}
        ROX_ADMIN_PASSWORD: ${{ inputs.rox-admin-password }}
        ROX_ADMIN_USERNAME: admin
        CENTRAL_IP: ${{ inputs.central-ip }}
        CLUSTER_API_ENDPOINT: https://${{ inputs.central-ip }}:443
        MONITORING_SUPPORT: "true"
        PAGERDUTY_INTEGRATION_KEY: ${{ inputs.pagerduty-integration-key }}
        KUBECONFIG: ${{ inputs.kubeconfig }}
        STACKROX_DIR: ${{ github.workspace }}
      run: |
        set -uo pipefail
        "${GITHUB_ACTION_PATH}/../../common/common.sh" \
          "${GITHUB_ACTION_PATH}/start-secured-cluster.sh"
      shell: bash
