apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - stackrox-monitoring-alertmanager:9093

    rule_files:
      - /etc/prometheus/rules_*.yml

    scrape_configs:
      - job_name: "kubernetes-pods"
        tls_config:
          insecure_skip_verify: false
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              own_namespace: true
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: node_name

      - job_name: "kubernetes-cadvisor"
        scheme: https
        metrics_path: /metrics/cadvisor
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

        metric_relabel_configs:
          - source_labels: [container]
            regex: berserker
            action: drop

      - job_name: stackrox
        tls_config:
          insecure_skip_verify: false
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              own_namespace: true
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: monitoring
          - source_labels: [__meta_kubernetes_endpoints_name]
            action: replace
            target_label: job
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_endpoint_node_name]
            action: replace
            target_label: node_name
