securedCluster:
  namespace: stackrox
  spec:
    sensor:
      resources:
        requests:
          memory: "3Gi"
          cpu: "2"
        limits:
          memory: "12Gi"
          cpu: "4"
    scanner:
      scannerComponent: Enabled
    processBaselines:
      autoLock: Enabled
    perNode:
      fileActivityMonitoring:
        mode: Enabled
    customize:
      envVars:
        - name: ROX_NETFLOW_BATCHING
          value: "true"
        - name: ROX_NETFLOW_CACHE_LIMITING
          value: "true"
    overlays:
      - apiVersion: apps/v1
        kind: DaemonSet
        name: collector
        patches:
          - path: spec.template.spec.containers[name:fact].env[-1]
            value: |
              name: FACT_PATHS
              value: "/tmp/data/**/*"
          - path: spec.template.spec.containers[name:fact].env[-1]
            value: |
              name: FACT_LOGLEVEL
              value: "info"
