name: Move a tag
description: Move a tag to a new position
inputs:
  sliding-tag:
    description: Tag
    required: true
  ref-name:
    description: Target Github reference name
    required: false
    default: "${{ github.ref_name }}"
  token:
    description: GitHub token
    required: false
    default: "${{ github.token }}"
  dry-run:
    description: Whether it is a dry-run
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - run: |
        set -uo pipefail
        "${{ github.action_path }}/../../common/common.sh" \
          "${{ github.action_path }}/move-tag.sh" \
          "${{ inputs.sliding-tag }}" \
          "${{ inputs.ref-name }}"
      shell: bash
