name: Install infractl
description: Download infractl to ~/.local/bin

runs:
  using: composite
  steps:
    - name: Download infractl
      shell: bash
      run: |
        mkdir -p ~/.local/bin
        curl --fail -sL https://infra.rox.systems/v1/cli/linux/amd64/upgrade \
        | jq -r ".result.fileChunk" \
        | base64 -d \
        > ~/.local/bin/infractl
        chmod +x ~/.local/bin/infractl
        echo "::debug::$(infractl --version)"
