name: Install infractl
description: Download infractl to ~/.local/bin

runs:
  using: composite
  steps:
    - name: Download and install infractl
      shell: bash
      run: "${GITHUB_ACTION_PATH}/install-infractl.sh"
