name: Create Cluster
description: Create a cluster on infra
inputs:
  token:
    description: Infra access token
    required: true
  flavor:
    description: Flavor (`qa-demo`, `gke-default`, `openshift-4-demo`...)
    required: true
  name:
    description: Cluster name ([a-z][a-z0-9-]{1,26}[a-z0-9])
    required: true
  lifespan:
    description: Cluster lifespan
    default: 48h
    required: false
  args:
    description: Comma separated flavor arguments. Ex. nodes=5,main-image=main:tag
    required: false
    default: ""
  wait:
    description: Whether to wait for the cluster readiness
    required: false
    default: "false"
  no-slack:
    description: Whether to skip sending Slack messages for lifecycle events
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - uses: stackrox/actions/infra/install-infractl@main

    - name: Validate the infractl install and its token
      shell: bash
      env:
        INFRA_TOKEN: "${{ inputs.token }}"
      run: |
        infractl whoami

    - name: Create Cluster
      shell: bash
      env:
        INFRA_TOKEN: "${{ inputs.token }}"
      run: |
        echo "::add-mask::$INFRA_TOKEN"
        set -uo pipefail
        "${{ github.action_path }}/../../common/common.sh" \
          "${{ github.action_path }}/create-cluster.sh" \
          "${{ inputs.flavor }}" \
          "${{ inputs.name }}" \
          "${{ inputs.lifespan }}" \
          "${{ inputs.wait }}" \
          "${{ inputs.no-slack }}" \
          "${{ inputs.args }}"
