name: Auto-merge PRs
description: Enable auto-merge for eligible PRs with specified labels

inputs:
  allowed-author:
    description: 'Author to filter PRs for auto-merge'
    required: false
    default: 'app/dependabot'
  allowed-base-branches:
    description: 'Allowed base branches for auto-merge'
    required: false
    default: '.*'
  dry-run:
    description: 'Whether to dry-run the auto-merge'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token with permissions to merge PRs and approve reviews'
    required: true
  label:
    description: 'Label to filter PRs for auto-merge'
    required: false
    default: 'auto-merge'
  limit:
    description: 'Maximum number of PRs to process per run.'
    required: false
    default: '50'
  repository:
    description: 'Repository in owner/repo format'
    required: false
    default: ${{ github.repository }}
  required-checks:
    description: 'Required checks to pass for auto-merge'
    required: false
    default: '.*'

runs:
  using: composite
  steps:
    - name: Find and process PRs with auto-merge labels
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        set -euo pipefail

        "${GITHUB_ACTION_PATH}/../../common/common.sh" \
          "${GITHUB_ACTION_PATH}/automerge.sh" \
          "${{ inputs.repository }}" \
          "${{ inputs.limit }}" \
          "${{ inputs.label }}" \
          "${{ inputs.allowed-author }}" \
          "${{ inputs.required-checks }}" \
          "${{ inputs.allowed-base-branches }}"
