name: Create demo clusters for version
on:
  workflow_call:
    inputs:
      version:
        description: Version of the images
        required: true
        type: string
      create-k8s-cluster:
        description: Create a GKE demo cluster
        default: false
        type: boolean
      create-os4-cluster:
        description: Create an Openshift 4 demo cluster
        default: false
        type: boolean
      create-long-cluster:
        description: Create a long-running cluster on RC1
        default: false
        type: boolean
      dry-run:
        description: Dry-run
        default: false
        type: boolean
      workflow-ref:
        description: Ref of the called workflow
        type: string
      kube-burner-config-ref:
        description: Ref of where the kube-burner config files can be found
        type: string
      kube-burner-config-repo:
        description: The repository where the kube-burner config files can be found
        type: string
      cluster-with-fake-load-name:
        description: The name of the long running cluster where the central deployment is run with a sensor that creates its own fake workload
        type: string
      cluster-with-real-load-name:
        description: The name of the long running cluster where collector is run with real workload
        type: string

env:
  main_branch: ${{github.event.repository.default_branch}}
  script_url: /repos/${{github.repository}}/contents/.github/workflows/scripts/common.sh?ref=${{ github.ref_name }}
  DRY_RUN: ${{ inputs.dry-run }}
  ACCEPT_RAW: "Accept: application/vnd.github.v3.raw"
  GH_TOKEN: ${{ github.token }}
  GH_NO_UPDATE_NOTIFIER: 1
  TIMEOUT_WAIT_FOR_IMAGES_SECONDS: 3600

jobs:
  run-parameters:
    name: Run parameters
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOF >>"$GITHUB_STEP_SUMMARY"
          Inputs:
          \`\`\`
          ${{toJSON(inputs)}}
          \`\`\`
          \`\`\`
          GitHub Event:
          ${{toJSON(github.event)}}
          \`\`\`

          EOF
