run-name: Move major tag ${{ github.ref_name }}

on:
  push:
    tags:
      - v*.*.*

jobs:
  move-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Initialize mandatory git config
        id: git-config
        run: |
          echo "sliding-tag=$(echo ${{ github.ref_name }} | cut -d . -f 1)" >> "$GITHUB_OUTPUT"
      - name: Move major version tag for ${{ github.ref_name }}
        uses: stackrox/actions/infra/create-cluster@tm/move-tag-workflow # TODO: change to main
        with:
          sliding-tag: ${{ steps.git-config.outputs.sliding-tag }}
          ref-name: ${{ github.ref_name }}
